version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd frontend && npm install && npm run build

  build-backend:
    docker:
      - image: circleci/node:13.8.0 # Assuming your backend is also NodeJS-based
    steps:
      - checkout
      - run: cd backend && npm install && npm run build

workflows:
  version: 2
  build:
    jobs:
      - build-frontend
      - build-backend
