# docker-compose.yml
version: "3"
services:
    database:
        image: "postgres"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=glee
        ports:
            - "5432:5432"
    pgadmin:
        image: "dpage/pgadmin4"
        environment:
            - PGADMIN_DEFAULT_EMAIL=root@fpt.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "5050:80"
        depends_on:
            - database
